language: node_js
node_js:
- '6.10'
install:
- npm install
script:
- npm run test
deploy:
  provider: npm
  email: "hekark@gmail.com"
  api_key:
    secure: "Hg/29Le/EPRkX/V/9TEWGhTpYuerYbvxcyjTryvkvvgn7ch9J2GySTNA1HPl/PM1SgnuNqAwmDxE9Ea+eMEA2yVQeeSp150buTvYEQdesh+3aI2aWQe2KQy0nk4w61aUGQswrx8WjnShyKZXGkDlct/8EzTIcHbMcLaqbRicTjgUYaVjBS7wGO8uknT20zhc5jRipvFXA7QjZzRcOXiyUAuK0p+TVnQTAy+h4QPCwJoCoCjo6jInwbnvUcJb4SNajOew3qI/G0Kxpwzbu41UM7jaEXtCK47KNjvD/SAWOyiCe4Jt/WVOXO+byjswU/50zkNG4sFPly7Y9/qJCrWFBgNA2Q59T9rM05a7EbyfzzXMhrR1ab0VRlTPtg3QaTD+U1LVIbVhmd5bSe57NAogtLx1yrF5A6C3yVIUh42s69lf47Q+vHxt4YjNm7Q+c6hr9KgqqqDC3v+jp6APuX+rSdkdBBVAVlOaZp15RbXyZozujM6kSqv7fKYKNN8IYLISFM0BFBFbsv3xrnTRFK10N1q1gpYMYTYEFW+ENDCOBP/n5ubbv4SvfH9XLjtSqL3s5SNuS/Ysi/h2vmIPQEmJ9VnT/Ae+AI/rOmArJlS4yPGWas+if53EFy4F/n24H4yhBEJRrDsUEo45d7dZTIlj5Bxehus4uGiuTJqEIJ14XJk="
  on:
    branch: master
